# Etape 2.1 : Nettoyage des donnees meteos avec Pandas

**Objectif** : Traiter des donnees structurees avec un langage de programmation

---
---

## Imports

In [1]:
import sys
import os
from pathlib import Path
from datetime import datetime
import pandas as pd
import numpy as np

---

## Chemins des données

In [2]:
# ==============================================================================================================
#                                                    DIRS
# ==============================================================================================================
DATA_DIR_PATH = (Path.cwd() / ".." / "data").resolve()
OUTPUT_DIR_PATH = (Path.cwd() / ".." / "output").resolve()

# ==============================================================================================================
#                                                  INPUTS
# ==============================================================================================================
METEO_RAW_FILE_DATA_PATH = os.path.join(DATA_DIR_PATH, "meteo_raw.csv")

## Check if inputs exists:
if not os.path.exists(METEO_RAW_FILE_DATA_PATH):
    print("Error: METEO_RAW_FILE_DATA_PATH does not exist:", METEO_RAW_FILE_DATA_PATH)
    sys.exit(1)

# ==============================================================================================================
#                                                OUTPUTS
# ==============================================================================================================
METEO_CLEAN_FILE_DATA_PATH = os.path.join(OUTPUT_DIR_PATH, "meteo_clean.csv")

---

## 3.1 Chargement du fichier weather_raw.csv avec Pandas (les données météo brutes)

In [3]:
## Chargement des données avec Pandas
df_meteo_raw = pd.read_csv(METEO_RAW_FILE_DATA_PATH)

## Affichage de quelques infos
print(f"- Shape: {df_meteo_raw.shape}")
print(f"- Colonnes: {df_meteo_raw.columns.tolist()}")
print()
# Info sur les types
print("- Infos sur les types : ")
df_meteo_raw.info()
print()
## Appercu des donnees
print("- Appercu des donnees : ")
df_meteo_raw.head(10)

- Shape: (252612, 7)
- Colonnes: ['commune', 'timestamp', 'temperature_c', 'humidite_pct', 'rayonnement_solaire_wm2', 'vitesse_vent_kmh', 'precipitation_mm']

- Infos sur les types :
<class 'pandas.DataFrame'>
RangeIndex: 252612 entries, 0 to 252611
Data columns (total 7 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   commune                  252612 non-null  str
 1   timestamp                252612 non-null  str
 2   temperature_c            251383 non-null  str
 3   humidite_pct             252612 non-null  float64
 4   rayonnement_solaire_wm2  252612 non-null  float64
 5   vitesse_vent_kmh         252612 non-null  float64
 6   precipitation_mm         252612 non-null  float64
dtypes: float64(4), str(3)
memory usage: 13.5 MB

- Appercu des donnees :

,commune,timestamp,temperature_c,humidite_pct,rayonnement_solaire_wm2,vitesse_vent_kmh,precipitation_mm
0,Saint-Etienne,09/15/2024 15:00:00,17.1,143.3,244.9,14.3,0.0
1,Bordeaux,21/07/2023 15:00,19.6,50.6,414.9,3.2,0.0
2,Montpellier,2023-09-18 20:00:00,18.3,65.7,218.4,13.6,0.0
3,Le Havre,01/03/2024 22:00:00,3.7,94.9,6.8,18.6,11.6
4,Lille,29/10/2024 20:00,14.0,42.9,781.8,4.0,0.0
5,Bordeaux,22/12/2023 13:00,4.4,36.9,796.4,6.1,0.0
6,Marseille,09/15/2023 21:00:00,22.5,86.8,5.8,32.6,0.0
7,Toulouse,30/05/2023 00:00,8.3,66.3,26.4,31.4,7.2
8,Bordeaux,2024-10-05T09:00:00,11.5,69.8,71.4,34.4,0.0
9,Toulon,2024-09-28T21:00:00,19.2,79.0,13.1,31.8,0.0

---

## 3.2 Identification et traitement des valeurs manquantes (Diagnostic de la qualite des donnees) :
- Interpolation linéaire pour température et humidité.
- Forward fill pour les precipitation_mm.

In [4]:
def quality_report(df, name="DataFrame"):
    print(f"RAPPORT QUALITE - {name}")
    print(f"- Lignes: {len(df):,}")
    print(f"- Colonnes: {len(df.columns)}")
    
    report = []
    for col in df.columns:
        total = len(df)
        missing = df[col].isna().sum() + (df[col] == '').sum() if df[col].dtype == 'object' else df[col].isna().sum()
        completude = (1 - missing / total) * 100
        unique = df[col].nunique()
        dtype = df[col].dtype
        
        report.append({
            'Colonne': col,
            'Type': str(dtype),
            'Manquants': missing,
            'Completude %': round(completude, 2),
            'Uniques': unique
        })
    
    return pd.DataFrame(report)

quality_report(df_meteo_raw, "Weather Raw")

RAPPORT QUALITE - Weather Raw
- Lignes: 252,612
- Colonnes: 7

                   Colonne     Type  Manquants  Completude %  Uniques
0                  commune      str          0        100.00       15
1                timestamp      str          0        100.00    69066
2            temperature_c      str       1229         99.51      810
3             humidite_pct  float64          0        100.00     1094
4  rayonnement_solaire_wm2  float64          0        100.00     8685
5         vitesse_vent_kmh  float64          0        100.00      401
6         precipitation_mm  float64          0        100.00      151

In [5]:
# Examiner les valeurs problematiques dans temperature_c
print("- Valeurs uniques non numeriques dans temperature_c:")
temp_non_numeric = df_meteo_raw[
    ~df_meteo_raw['temperature_c'].astype(str).str.match(r'^-?[0-9]+[.,]?[0-9]*$', na=False)
]['temperature_c'].unique()
print(temp_non_numeric)

- Valeurs uniques non numeriques dans temperature_c:
<StringArray>
[nan]
Length: 1, dtype: str

In [6]:
## Valeurs aberrantes de temperature_c
df_temp = df_meteo_raw.copy()
df_temp['temperature_c'] = pd.to_numeric(
    df_temp['temperature_c'].astype(str).str.replace(',', '.'), 
    errors='coerce' # Toute valeur invalide ("NA", "erreur", "null", vide) => NaN
)

print("- Distribution temperature:")
print(df_temp['temperature_c'].describe())

print("\n- Nombres des valeurs aberrantes de temperature :")
print(f"    - Temperatures < -40: {(df_temp['temperature_c'] < -40).sum()}")
print(f"    - Temperatures > 50: {(df_temp['temperature_c'] > 50).sum()}")

- Distribution temperature:
count    251383.000000
mean         15.101909
std          10.996268
min         -70.000000
25%           8.700000
50%          14.500000
75%          21.000000
max         100.000000
Name: temperature_c, dtype: float64

- Nombres des valeurs aberrantes de temperature :
    - Temperatures < -40: 695
    - Temperatures > 50: 1282

In [7]:
## Humidite (humidite_pct) hors bornes
df_temp['humidite_pct'] = pd.to_numeric(df_temp['humidite_pct'], errors='coerce')

print("\n- Distribution humidite:")
print(df_temp['humidite_pct'].describe())

print(f"\n- Humidite > 100%: {(df_temp['humidite_pct'] > 100).sum()}")
print(f"- Humidite < 0%: {(df_temp['humidite_pct'] < 0).sum()}")

- Distribution humidite:
count    252612.00000
mean         63.03070
std          19.49437
min          30.00000
25%          46.50000
50%          62.80000
75%          79.10000
max         150.00000
Name: humidite_pct, dtype: float64

- Humidite > 100%: 1801
- Humidite < 0%: 0

---

## 3.3 Nettoyage des donnees meteo

In [8]:
def parse_timestamp(ts):
    """Parse les timestamps multi-formats."""
    if pd.isna(ts):
        return pd.NaT
    
    # formats = [
    #     "%Y-%m-%d %H:%M:%S",
    #     "%d/%m/%Y %H:%M",
    #     "%m/%d/%Y %H:%M:%S",
    #     "%Y-%m-%dT%H:%M:%S",
    # ]
    formats = [
        "%Y-%m-%d %H:%M:%S",
        "%d/%m/%Y %H:%M:%S",  
        "%d/%m/%Y %H:%M",
        "%m/%d/%Y %H:%M:%S",
        "%m/%d/%Y %H:%M",     
        "%Y-%m-%dT%H:%M:%S",
    ]
    
    for fmt in formats:
        try:
            return datetime.strptime(str(ts), fmt)
        except ValueError:
            continue
    
    return pd.NaT

df_meteo = df_meteo_raw.copy()

# Parser les timestamps
print("[1/5] Parsing des timestamps ...")
df_meteo['timestamp'] = df_meteo['timestamp'].apply(parse_timestamp)
invalid_ts = df_meteo['timestamp'].isna().sum()
print(f"    - Timestamps invalides: {invalid_ts}")

# Supprimer les lignes sans timestamp valide
df_meteo = df_meteo.dropna(subset=['timestamp'])

[1/5] Parsing des timestamps ...
    - Timestamps invalides: 0

In [9]:
# --- Convertir les colonnes numeriques
print("\n[2/5] Conversion des colonnes numeriques ...")

## Temperature (remplacer virgule par point)
df_meteo['temperature_c'] = pd.to_numeric(
    df_meteo['temperature_c'].astype(str).str.replace(',', '.'),
    errors='coerce' # Si une valeur ne peut pas être convertie en nombre, transforme-la en NaN
)

## Autres colonnes
df_meteo['humidite_pct'] = pd.to_numeric(df_meteo['humidite_pct'], errors='coerce')
df_meteo['rayonnement_solaire_wm2'] = pd.to_numeric(df_meteo['humidite_pct'], errors='coerce')
df_meteo['vitesse_vent_kmh'] = pd.to_numeric(df_meteo['vitesse_vent_kmh'], errors='coerce')
df_meteo['precipitation_mm'] = pd.to_numeric(df_meteo['precipitation_mm'], errors='coerce')

print("  Conversions effectuees.")

[2/5] Conversion des colonnes numeriques ...
  Conversions effectuees.

In [10]:
# --- Corriger les valeurs aberrantes
print("\n[3/5] Correction des valeurs aberrantes ...")

# Temperatures hors [-40, 50] -> NaN
temp_outliers = ((df_meteo['temperature_c'] < -40) | (df_meteo['temperature_c'] > 50)).sum()
df_meteo.loc[
    (df_meteo['temperature_c'] < -40) | (df_meteo['temperature_c'] > 50),
    'temperature_c'
] = np.nan
print(f"    - Nombre de 'temperatures' aberrantes (hors [-40, 50]) transformées en NaN : {temp_outliers}")

# Humidite hors [0, 100] -> clipper
humidity_outliers = ((df_meteo['humidite_pct'] < 0) | (df_meteo['humidite_pct'] > 100)).sum()
df_meteo['humidite_pct'] = df_meteo['humidite_pct'].clip(0, 100)
print(f"    - Nombre de 'humidite' abérrantes (hors [0, 100]) clippee [0, 100]: {humidity_outliers}")

# Rayonnement solaire negatif -> 0
rayonnement_outliers = ((df_meteo['rayonnement_solaire_wm2'] < 0)).sum()
df_meteo['rayonnement_solaire_wm2'] = df_meteo['rayonnement_solaire_wm2'].clip(lower=0)
print(f"    - Nombre de 'rayonnements solaire' abérrents (< 0) transformées en 0 : {rayonnement_outliers}")

[3/5] Correction des valeurs aberrantes ...
    - Nombre de 'temperatures' aberrantes (hors [-40, 50]) transformées en NaN : 1977
    - Nombre de 'humidite' abérrantes (hors [0, 100]) clippee [0, 100]: 1801
    - Nombre de 'rayonnements solaire' abérrents (< 0) transformées en 0 : 0

In [11]:
# --- Traiter les valeurs manquantes
print("[4/5] Traitement des valeurs manquantes ...")

# Trier par commune et timestamp pour l'interpolation
df_meteo = df_meteo.sort_values(['commune', 'timestamp'])

# Interpolation lineaire pour temperature et humidite ... (par commune) (les autres colonnes au choix) => (Variables continues et progressives)
for col in ['temperature_c', 'humidite_pct', 'rayonnement_solaire_wm2', 'vitesse_vent_kmh']:
    before_na = df_meteo[col].isna().sum()
    df_meteo[col] = df_meteo.groupby('commune')[col].transform(
        lambda x: x.interpolate(method='linear', limit_direction='both')
    )
    after_na = df_meteo[col].isna().sum()
    print(f"  - {col}: {before_na} -> {after_na} NaN (interpoles: {before_na - after_na})")

# Forward fill pour precipitation_mm => (Variables cumulatives)
before_na = (df_meteo['precipitation_mm'].isna() | (df_meteo['precipitation_mm'] == '')).sum()
df_meteo['precipitation_mm'] = df_meteo['precipitation_mm'].replace('', np.nan)
df_meteo['precipitation_mm'] = df_meteo.groupby('commune')['precipitation_mm'].transform(
    lambda x: x.ffill().bfill()
)
after_na = df_meteo['precipitation_mm'].isna().sum()
print(f"  - precipitation_mm: {before_na} -> {after_na} NaN (forward filled)")

[4/5] Traitement des valeurs manquantes ...
  - temperature_c: 3206 -> 0 NaN (interpoles: 3206)
  - humidite_pct: 0 -> 0 NaN (interpoles: 0)
  - rayonnement_solaire_wm2: 0 -> 0 NaN (interpoles: 0)
  - vitesse_vent_kmh: 0 -> 0 NaN (interpoles: 0)
  - precipitation_mm: 0 -> 0 NaN (forward filled)

In [12]:
## 5. Ajouter des colonnes temporelles
print("[5/5] Ajout des colonnes temporelles ...")

df_meteo['jour'] = df_meteo['timestamp'].dt.date
df_meteo['mois'] = df_meteo['timestamp'].dt.month
df_meteo['saison'] = df_meteo['mois'].map({
    12: 'Hiver', 1: 'Hiver', 2: 'Hiver',
    3: 'Printemps', 4: 'Printemps', 5: 'Printemps',
    6: 'Ete', 7: 'Ete', 8: 'Ete',
    9: 'Automne', 10: 'Automne', 11: 'Automne'
})

df_meteo['jour_de_semaine'] = df_meteo['timestamp'].dt.dayofweek

print("  - Colonnes ajoutees: jour, mois, saison, jour_de_semaine")

print("  - Appercu des données meteo nettoyées : ")
df_meteo.head(10)

[5/5] Ajout des colonnes temporelles ...
  - Colonnes ajoutees: jour, mois, saison, jour_de_semaine
  - Appercu des données meteo nettoyées :

,commune,timestamp,temperature_c,humidite_pct,rayonnement_solaire_wm2,vitesse_vent_kmh,precipitation_mm,jour,mois,saison,jour_de_semaine
242272,Bordeaux,2023-01-01 00:00:00,8.5,43.9,43.9,0.2,0.0,2023-01-01,1,Hiver,6
233980,Bordeaux,2023-01-01 01:00:00,2.7,39.7,39.7,21.5,5.3,2023-01-01,1,Hiver,6
108665,Bordeaux,2023-01-01 02:00:00,6.2,78.9,78.9,13.1,0.0,2023-01-01,1,Hiver,6
5904,Bordeaux,2023-01-01 03:00:00,10.3,64.2,64.2,0.6,14.7,2023-01-01,1,Hiver,6
23544,Bordeaux,2023-01-01 04:00:00,0.9,36.4,36.4,35.6,0.0,2023-01-01,1,Hiver,6
89966,Bordeaux,2023-01-01 05:00:00,7.9,66.0,66.0,0.3,0.0,2023-01-01,1,Hiver,6
168449,Bordeaux,2023-01-01 06:00:00,1.6,40.2,40.2,24.3,0.0,2023-01-01,1,Hiver,6
51384,Bordeaux,2023-01-01 07:00:00,4.9,87.9,87.9,27.9,0.0,2023-01-01,1,Hiver,6
88813,Bordeaux,2023-01-01 08:00:00,8.4,43.4,43.4,38.8,0.1,2023-01-01,1,Hiver,6
30506,Bordeaux,2023-01-01 09:00:00,10.1,83.8,83.8,25.4,0.0,2023-01-01,1,Hiver,6

In [13]:
# --- Rapport apres nettoyage
quality_report(df_meteo, "Weather Clean")

RAPPORT QUALITE - Weather Clean
- Lignes: 252,612
- Colonnes: 11

                    Colonne            Type  Manquants  Completude %  Uniques
0                   commune             str          0         100.0       15
1                 timestamp  datetime64[us]          0         100.0    17544
2             temperature_c         float64          0         100.0     1092
3              humidite_pct         float64          0         100.0      652
4   rayonnement_solaire_wm2         float64          0         100.0     1094
5          vitesse_vent_kmh         float64          0         100.0      401
6          precipitation_mm         float64          0         100.0      151
7                      jour          object          0         100.0      731
8                      mois           int32          0         100.0       12
9                    saison             str          0         100.0        4
10          jour_de_semaine           int32          0         100.0        7

---

## Creation du dataset nettoye output/meteo_clean.csv

In [14]:
# --- Sauvegarde
df_meteo.to_csv(METEO_CLEAN_FILE_DATA_PATH, index=False)
print("=> Création avec succès du dataset nettoyé 'output/meteo_clean.csv'")

=> Création avec succès du dataset nettoyé 'output/meteo_clean.csv'

---

## Libérer la mémoire (Optionnel)

In [15]:

del df_meteo_raw
del df_meteo